apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "code-sign-identity-info"
  description: "code-sign-identity-info"
  annotations:
    gcp.bitrise.io/dev-project-id: ip-release-automation-dev
    gcp.bitrise.io/dev-service-account: code-sign-identity-info@ip-release-automation-dev.iam.gserviceaccount.com
    gcp.bitrise.io/prod-project-id: ip-release-automation-prod
    gcp.bitrise.io/prod-service-account: code-sign-identity-info@ip-release-automation-prod.iam.gserviceaccount.com
spec:
  type: service
  lifecycle: experimental
  owner: "release-automation-engineers"
  system: "release-automation"
  dependsOn:
    []
    

