FROM golang:1.22-alpine3.20 AS builder

ENV GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64

WORKDIR build

COPY . .

RUN go build -o /go-app ./...


FROM alpine:3.20

RUN apk add -u ca-certificates && rm -rf /var/cache/apk/*

EXPOSE 3000

COPY --from=builder /go-app .

CMD ["/go-app"]
